# Generated by Django 2.2.7 on 2019-11-24 15:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ordered'), (2, 'In progress'), (3, 'Delivered')])),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.PositiveSmallIntegerField(choices=[(1, 'Margarita'), (2, 'Marinara'), (3, 'Salami')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='ordering.Order')),
            ],
            options={
                'unique_together': {('order', 'flavor')},
            },
        ),
        migrations.CreateModel(
            name='PizzaOrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveSmallIntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')])),
                ('quantity', models.PositiveSmallIntegerField()),
                ('pizza_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ordering.PizzaOrder')),
            ],
        ),
    ]
